spring:
  jmx:
    enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

info:
  app:
    name: Spring Actuator
    version: 1.0.0-SNAPSHOT
  blog:
    link: http://letstalkaboutjava.blogspot.com/
    author: Sebastian Malaca

management:
  server:
    port: 8123
  endpoints:
    web:
      base-path: /app-monitoring
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
      db:
        enabled: true
