topics:
  simple:
    topic-one: topic-one
    topic-two: topic-two
    topic-three: topic-three
    topic-four: topic-four
  with-header:
    topic-five: topic-five

spring:
  kafka:
    consumer:
      group-id: group-one